app:
  build: .
  command: python -u app.py
  ports:
    - "50505:50505"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: test_mongodb
  environment:
    - MONGO_INITDB_DATABASE=books_db
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=Aleyna7174
  ports:
    - 27017:27017

    