apiVersion: v1
kind: Service
metadata:
  labels:
    app: databaseproject
  name: databaseproject-mongodb-service
spec:
  selector:
    app: databaseproject
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
